version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - goloroden
    labels:
      - Dependencies
    commit-message:
      prefix: fix
    groups:
      gradle:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/docker"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - goloroden
    labels:
      - Dependencies
    commit-message:
      prefix: chore
    groups:
      docker:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    cooldown:
      default-days: 7
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - goloroden
    labels:
      - Dependencies
    commit-message:
      prefix: chore
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
