[versions]
jackson = "3.2.3"
jacoco = "0.8.15"
junit = "6.1.3"
maven-publish = "0.37.0"
palantir-java-format = "2.102.0"
slf4j = "2.0.20"
spotless = "8.10.3"
testcontainers = "2.0.5"

[libraries]
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jacoco-agent = { module = "org.jacoco:org.jacoco.agent", version.ref = "jacoco" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
maven-publish-gradle-plugin = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }
palantir-java-format = { module = "com.palantir.javaformat:palantir-java-format", version.ref = "palantir-java-format" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
